local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
 
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
 
amazon:
  service: S3
  access_key_id: ENV["ACCESS_KEY"]
  secret_access_key: ENV["SECRET_KEY"]
  bucket: "rubyclass"
  region: "us-east-2" # e.g. 'us-east-1'